        
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        show_sql: true
        format_sql: true
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
        jdbc:
          lob:
            non_contextual_creation: true
    use-new-id-generator-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/petstore
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10



